version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: local_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david123
      - POSTGRES_DB=sensordb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
